name: expl_rationalizing
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab>=3.2.8,<3.3
  - matplotlib>=3.5.1,<3.6
  - pandas>=1.3.5,<1.4
  - python>=3.10.1,<3.11
  - statsmodels>=0.13.1,<0.14

